version: "3.9"
services:
  _service:
    image: temilola/turbomedics-api:latest  # Replace 'latest' with the desired tag
    ports:
      - "5000:5000"
    depends_on:
      - my_redis_service
      - my_postgres_service
    environment:
      DB_HOST: my_postgres_container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: Un53cur3Pa55w0rd
      DB_DATABASE: turbomeddb
      REDIS_HOST: my_redis_container
      REDIS_PORT: 6379
      REDIS_DB: 0
      ROOT_URL: http://localhost:5000  # You can modify this as needed
      PORT: 5000
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ""  # Update if needed
    restart: always

  my_redis_service:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - "6379:6379"
    expose:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

  my_postgres_service:
    image: postgres
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: turbomeddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Un53cur3Pa55w0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres_data:  # volume for PostgreSQL data
  redis_data:  # volume for Redis data
